import sys
import os
import asyncio
import pandas as pd

# Ensure src is in the python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.database.engine_v3 import init_v3_db
from src.mcp_tools.kvs_tools import write_layer, read_layer
import json

async def main():
    print("1. Initializing Semantic KVS Database...")
    await init_v3_db()

    print("\n2. Creating a Pandas DataFrame (2D Data)...")
    # Imagine this data was scraped, generated by AI, or loaded from CSV
    df = pd.DataFrame({
        "id": [101, 102, 103],
        "name": ["Alice", "Bob", "Charlie"],
        "department": ["Engineering", "Sales", "Marketing"],
        "salary": [85000, 72000, 68000]
    })
    print(df)

    print("\n3. Storing the ENTIRE DataFrame into the KVS at once...")
    # Convert DataFrame to JSON (orient='records' keeps it as a list of dicts)
    json_payload = df.to_json(orient='records')
    await write_layer("hr:employees:2026", "dataframe", json_payload)
    print("-> Successfully swallowed the 2D array whole!")

    print("\n4. Retrieving the DataFrame from the KVS...")
    # Read the layer back
    layer_str = await read_layer("hr:employees:2026")
    layer_data = json.loads(layer_str)
    
    # Reconstruct the Pandas DataFrame instantly
    restored_df = pd.DataFrame(layer_data["payload"])
    print("\nRestored DataFrame:")
    print(restored_df)
    
    print("\nConclusion: Zero ORM mapping. Zero SQL JOINs. Pure Vectorized Persistence.")

if __name__ == "__main__":
    asyncio.run(main())
